<?php


$GLOBALS["BIND9_DATABLOCK_VALUES"] = array(
    "allow-transfer",
);

function bind9_zoneconfig_decode($file){
    // $config=array(
    //     "raw" => "",
    // );
    $config = array();
    $handle = fopen($file, "r");
    $currentZone = "";
    $currentBlock = "";
    $readingDataBlock = false;
    if ($handle) {
        while (($x = fgets($handle)) !== false) {
            
            if(str_starts_with($x, "//")){
                continue;
            }
            // echo $x;
            // $config["raw"].=$x;

            if(str_starts_with($x, "zone")){
                $match="";
                preg_match("/\".*\"/", $x, $match);
                $match = str_replace("\"", "", $match);
                $currentZone = $match[0];
                if(!isset($config["zones"])){
                    $config["zones"] = array();
                }
                array_push($config["zones"], $currentZone);
                if(!isset($config[$currentZone])){
                    $config[$currentZone] = array();
                }
                continue;
            }

            
            foreach($GLOBALS["BIND9_DATABLOCK_VALUES"] as $key => $value){
                if(str_contains($x, $value)){
                    // echo "X: $x contiene $value";
                    $readingDataBlock = true;
                    $currentBlock = $x;
                }
            }

            if($readingDataBlock){
                $match="";
                $pattern="/\}(\s|\n|\r|\t|\f)*(;)/";
                preg_match($pattern, $currentBlock,$match);
                if(count($match) == 0){
                    if($currentBlock != $x){
                        $currentBlock .= $x;
                    }
                    
                    preg_match($pattern, $currentBlock,$match);
                    if(count($match) == 0) continue;
                }
                // echo "Data block:" . $currentBlock . "\n";
                

                $match="";
                $currentBlock = str_replace("\n", "", $currentBlock);
                preg_match("/\{.*\}/", $currentBlock, $match);
                $value = str_replace("{", "", $match[0]);
                $value = str_replace("}", "", $value);

                preg_match("/^\s*(\w+|-)+/", $currentBlock, $match);
                $key = trim($match[0]);
                
                $values = explode(";", $value);
                // var_dump($value);
                // var_dump($currentBlock);
                foreach($values as $k => $val){
                    $val = trim($val);
                    if(empty($val)){
                        unset($values[$k]);
                    }
                }

                $config[$currentZone][$key] = $values;
                $readingDataBlock = false;
                continue;
            }

            $pattern="/\}(\s|\n|\r|\t|\f)*(;)/";
            $match = "";
            preg_match($pattern, $x, $match);
            if(count($match) > 0){
                continue;
            }

            if(empty(trim($x))) continue;

            $c = explode(" ", $x);
            // var_dump($c);
            foreach($c as $key => &$value){
                $value = trim($value);
                $value = str_replace(";", "", $value);
                $value = str_replace("\"", "", $value);
                if(empty($value))
                    unset($c[$key]);
            }
            $c = array_values($c);
            // var_dump($c);
            $val="";
            for($x = 1; $x < count($c); $x++){
                $val .= $c[$x];
            }

            // var_dump($c[0]);
            $config[$currentZone][$c[0]]=$val;

        }

        fclose($handle);
    }
    if(!isset($config["zones"])){
        $config["zones"] = array();
    }
    return $config;
}

function bind9_zoneconfig_encode($zones){
    $out="//Zone file generated by Light Basic Bind9 API\n";
    foreach($zones as $key => $zonedata ){
        if($key == "zones") continue;
        $out .= "zone \"$key\" IN {\n";
        foreach($zonedata as $zonedata_key => $field_data){
            if(!is_array($field_data)){
                if(file_exists($field_data)){
                    $out .= "   " . $zonedata_key . " " . "\"" . $field_data . "\";\n";
                }else{
                    $out .= "   " . $zonedata_key . " " . $field_data . ";\n";
                }
            }else{
                $out .= "   " . $zonedata_key . " { ";
                foreach($field_data as $fdk => $fdv){
                    $out .= "$fdv; ";
                }
                $out .=  " }; \n";
            }
        }
        $out .= "};\n\n";
    }
    if(strlen($out) < 3){
        return null;
    }else{
        return $out;
    }
}

enum BIND9_PARSER_CTX : string {
    case DEFAULT="DEFAULT";
    case E_TTL="EXPECTING TTL";
    case E_TTL_VALUE="EXPECTING TTL VALUE";
    case E_START_OF_AUTHORITY="EXPECTING START OF AUTHORITY";
    case E_DATABASE_CONFIG="EXPECTING DATABASE CONFIGURATION";
    case E_BEGIN_RECORD="EXPECTING BEGINING OF RECORD ENTRY";
    case E_RECORD_TTL="EXPECTING RECORD TTL";
    case E_RECORD_IN="EXPECTING RECORD IN";
    case E_RECORD_TYPE="EXPECTING RECORD TYPE";
    case E_RECORD_DATA="EXPECTING RECORD DATA";
}

enum DNSDBS : string {
    case DEFAULT_TTL="DEFAULT_TTL";
    case START_OF_AUTHORITY="SOA";
    case START_MAIN_SERVER="SOA_SERVER";
    case SERIAL="SERIAL";
    case REFRESH="REFRESH";
    case RETRY="RETRY";
    case EXPIRE="EXPIRE";
    case NEGATIVE_CACHE_TTL="NEGATIVE_CACHE_TTL";
    case RECORDSET="recordset";
    case RECORDSET_TYPES="types";
    case RECORDSET_VALUES="values";
    case RECORDSET_TTL="ttl";
    case RECORDSET_VALUE="value";
}

//removes comments and empty lines
function bind9_parser_cleanComments(&$buffer){
    $buffer = preg_replace("/;.*/", "", $buffer);
    $buffer = preg_replace('/^[ \t]*[\r\n]+/m', '', $buffer);
}

//read the data from the current context and clears the buffer
function bind9_parser_evalContext_buffer(&$buffer, &$database, $context){

    switch($context){

        case BIND9_PARSER_CTX::E_TTL:{
            $buffer = "";
            break;
        }

        case BIND9_PARSER_CTX::E_TTL_VALUE:{
            bind9_parser_cleanComments($buffer);
            $buffer = preg_replace("/[^0-9]+/", "", $buffer);
            $database[DNSDBS::DEFAULT_TTL->value]=(int)$buffer;
            $buffer="";
            break;
        }

        case BIND9_PARSER_CTX::E_START_OF_AUTHORITY:{
            bind9_parser_cleanComments($buffer);
            $buffer = trim($buffer);
            $buffer = preg_split("/\s+/", $buffer);
            $database[DNSDBS::START_OF_AUTHORITY->value]=$buffer[0];
            $database[DNSDBS::START_MAIN_SERVER->value]=$buffer[1];
            $buffer = "";
            break;
        }

        case BIND9_PARSER_CTX::E_DATABASE_CONFIG:{
            bind9_parser_cleanComments($buffer);
            $buffer = trim($buffer);
            $buffer = preg_replace("/[\r\n]/", "", $buffer);
            $buffer = preg_split("/\s+/", $buffer);
            $database[DNSDBS::SERIAL->value]=$buffer[0];
            $database[DNSDBS::REFRESH->value]=$buffer[1];
            $database[DNSDBS::RETRY->value]=$buffer[2];
            $database[DNSDBS::EXPIRE->value]=$buffer[3];
            $database[DNSDBS::NEGATIVE_CACHE_TTL->value]=$buffer[4];
            $database[DNSDBS::RECORDSET->value]=array();
            $buffer = "";
            break;
        }

        case BIND9_PARSER_CTX::E_BEGIN_RECORD:{
            bind9_parser_cleanComments($buffer);
            $buffer = trim($buffer);
            if($buffer == "@"){
                $buffer = $database[DNSDBS::START_OF_AUTHORITY->value];
            }
            if(!isset($database[DNSDBS::RECORDSET->value][$buffer])){
                $database[DNSDBS::RECORDSET->value][$buffer] = array();
                $database[DNSDBS::RECORDSET->value]["```r"]=$buffer;
            }
            $buffer = "";
            break;
        }

        case BIND9_PARSER_CTX::E_RECORD_TTL:{
            bind9_parser_cleanComments($buffer);
            $buffer = trim($buffer);
            $buffer = preg_replace("/[^0-9]/", "", $buffer);
            $database[DNSDBS::RECORDSET->value]["```r-ttl"]=(int)$buffer;
            $buffer = "";
            break;
        }

        case BIND9_PARSER_CTX::E_RECORD_TYPE:{
            bind9_parser_cleanComments($buffer);
            $buffer = trim($buffer);
            $database[DNSDBS::RECORDSET->value]["```r-type"]="$buffer";
            $buffer = "";
            if(!isset($database[DNSDBS::RECORDSET->value]["```r-ttl"]) || $database[DNSDBS::RECORDSET->value]["```r-ttl"] == 0){
                $database[DNSDBS::RECORDSET->value]["```r-ttl"] = $database[DNSDBS::DEFAULT_TTL->value];
            }
            // neatDump($buffer);
            
            break;
        }

        case BIND9_PARSER_CTX::E_RECORD_DATA:{
            $data = trim($buffer);
            $buffer = "";
            $type = $database[DNSDBS::RECORDSET->value]["```r-type"];
            $ttl = $database[DNSDBS::RECORDSET->value]["```r-ttl"];
            $entry = $database[DNSDBS::RECORDSET->value]["```r"];
            $database[DNSDBS::RECORDSET->value]["```r-ttl"] = 0;

            if(!isset($database[DNSDBS::RECORDSET->value][$entry][DNSDBS::RECORDSET_TYPES->value])){
                $database[DNSDBS::RECORDSET->value][$entry][DNSDBS::RECORDSET_TYPES->value] = array();
            }
            if(!in_array($type, $database[DNSDBS::RECORDSET->value][$entry][DNSDBS::RECORDSET_TYPES->value])){
                array_push($database[DNSDBS::RECORDSET->value][$entry][DNSDBS::RECORDSET_TYPES->value], $type);
            }

            if(!isset($database[DNSDBS::RECORDSET->value][$entry][$type][DNSDBS::RECORDSET_VALUES->value]) ){
                $database[DNSDBS::RECORDSET->value][$entry][$type] = array();
            }
            array_push($database[DNSDBS::RECORDSET->value][$entry][$type],
                array(
                    DNSDBS::RECORDSET_VALUE->value => $data,
                    DNSDBS::RECORDSET_TTL->value => $ttl
                )
            );
            
            
            break;
        }
    }
}

//returns next context and removes the keyword from the buffer if buffer is found to tontain the next context switch
function bind9_parser_matchNext(&$buffer, $context){
    switch($context){
        case BIND9_PARSER_CTX::DEFAULT:{
            
            if(preg_match("/\$/", $buffer)){
                return BIND9_PARSER_CTX::E_TTL;
            }

            break;
        }

        case BIND9_PARSER_CTX::E_TTL:{
            $match="/.*(TTL).*/";
            if(preg_match($match, $buffer)){
                $buffer = preg_replace($match, "", $buffer);
                return BIND9_PARSER_CTX::E_TTL_VALUE;
            }
            break;
        }

        case BIND9_PARSER_CTX::E_TTL_VALUE:{
            $match="/.*(@).+(IN).+(SOA)/";
            if(preg_match($match, $buffer)){
                $buffer = preg_replace($match, "", $buffer);
                return BIND9_PARSER_CTX::E_START_OF_AUTHORITY;
            }
            break;
        }

        case BIND9_PARSER_CTX::E_START_OF_AUTHORITY:{
            $match="/\(/";
            if(preg_match($match, $buffer)){
                $buffer = preg_replace($match, "", $buffer);
                return BIND9_PARSER_CTX::E_DATABASE_CONFIG;
            }
            break;
        }

        case BIND9_PARSER_CTX::E_DATABASE_CONFIG:{
            $match="/\)/";
            if(preg_match($match, $buffer)){
                $buffer = preg_replace($match, "", $buffer);
                return BIND9_PARSER_CTX::E_BEGIN_RECORD;
            }
            break;
        }

        case BIND9_PARSER_CTX::E_BEGIN_RECORD:{
            $match="/^@/m";
            if(preg_match($match, $buffer)){
                // $buffer = preg_replace($match, "", $buffer);
                return BIND9_PARSER_CTX::E_RECORD_TTL;
            }

            $match="/^[0-9a-zA-Z-]+[0-9a-zA-Z.-]+\s+/m";
            if(preg_match($match, $buffer)){
                // $buffer = preg_replace($match, "", $buffer);
                return BIND9_PARSER_CTX::E_RECORD_TTL;
            }
            break;
        }

        case BIND9_PARSER_CTX::E_RECORD_TTL:{
            // we check both for record TTL and IN as record TTL may not necessarily be set
            $match="/\s+[0-9]+\s+/";
            if(preg_match($match, $buffer)){
                // $buffer = preg_replace($match, "", $buffer);
                return BIND9_PARSER_CTX::E_RECORD_IN;
            }

            $match="/\s+IN\s+/";
            if(preg_match($match, $buffer)){
                $buffer = preg_replace($match, "", $buffer);
                return BIND9_PARSER_CTX::E_RECORD_TYPE;
            }
            break;
        }

        case BIND9_PARSER_CTX::E_RECORD_IN:{
            $match="/IN+\s/";
            if(preg_match($match, $buffer)){
                $buffer = preg_replace($match, "", $buffer);
                return BIND9_PARSER_CTX::E_RECORD_TYPE;
            }
            break;
        }

        case BIND9_PARSER_CTX::E_RECORD_TYPE:{
            $match="/\s+[A-Za-z]+\s+/";
            if(preg_match($match, $buffer)){
                return BIND9_PARSER_CTX::E_RECORD_DATA;
            }
            break;
        }

        case BIND9_PARSER_CTX::E_RECORD_DATA:{
            $match="/.+(\n\r|\r\n|\n)$/";
            if(preg_match($match, $buffer)){
                return BIND9_PARSER_CTX::E_BEGIN_RECORD;
            }
            break;
        }
    }
    return false;
}

function bind9_zonedb_decode($file){
    $database = array();
    $handle = fopen($file, "r");
    $buffer = "";
    $nextContext=null;
    $context=BIND9_PARSER_CTX::DEFAULT;
    if ($handle) {
        while (($x = fgetc($handle)) !== false) {

            $buffer .= $x;

            if(($nextContext = bind9_parser_matchNext($buffer, $context))!== false){
                bind9_parser_evalContext_buffer($buffer, $database, $context);
                $context = $nextContext;
            }

        }


        if(count($database) > 0){
            // neatDump("PARSED DATABASE WAS::::::");
            // neatDump($database);
            unset($database[DNSDBS::RECORDSET->value]["```r"]);
            unset($database[DNSDBS::RECORDSET->value]["```r-ttl"]);
            unset($database[DNSDBS::RECORDSET->value]["```r-type"]);
            return $database;
        }
    }
    
    return null;
}

function bind9_zonedb_encode($dbarray){
    $out = ";       Zone Database Generated by Light Bind9 Basic API\n";
    $out .= "\n\n;------------------------------- DB CFG\n";
    //Default TTL
    $out .= "\$TTL      " . $dbarray["DEFAULT_TTL"] . "\n";

    if(!str_ends_with($dbarray["SOA"], ".")){
        $dbarray["SOA"] = $dbarray["SOA"] . ".";
    }
    //Generate SOA
    $out .= "@      IN      SOA     " . $dbarray["SOA"] . "      " . $dbarray["SOA_SERVER"] . " (\n";
    $out .= "                       " . $dbarray["SERIAL"] . "      ; SERIAL\n";
    $out .= "                       " . $dbarray["REFRESH"] . "      ; REFRESH\n";
    $out .= "                       " . $dbarray["RETRY"] . "      ; RETRY\n";
    $out .= "                       " . $dbarray["EXPIRE"] . "      ; EXPIRE\n";
    $out .= "                       " . $dbarray["NEGATIVE_CACHE_TTL"] . " )     ; NEGATIVE_CACHE_TTL\n";
    
    $out .= "\n\n;------------------------------- RECORDSET\n\n\n";

    $default_ttl = $dbarray["DEFAULT_TTL"];

    $blankSpaces=0;
    foreach($dbarray["recordset"] as $dbarraykey => $record){
        $len = strlen($dbarraykey);
        if($len >  $blankSpaces){
            $blankSpaces = $len;
        }
    }
    $blankSpacesCount = $blankSpaces;
    $blankSpaces = "";

    foreach($dbarray["recordset"] as $dbarrykey => $record){
        $out .= ";----------- " . "$dbarrykey\n";
        foreach($record["types"] as $recordType){
            foreach($record[$recordType] as $entry){
                $ttl = $entry["ttl"];
                if($ttl == $default_ttl){
                    $ttl = "";
                }

                $recName = $dbarrykey;
                if($recName == $dbarray["SOA"]){
                    $recName = "@";
                }

                //calculate blank spaces for the record so they lign up neatly
                $curSpaces = $blankSpacesCount - strlen($recName) + 4;
                $blankSpaces = "";
                for($x = 0; $x < $curSpaces; $x++) {
                    $blankSpaces .= " ";
                }

                //calculate blank spaces for the record type so they lign up neatly
                $curSpaces = 10 - strlen($recordType) + 4;
                $recordBlankSpaces = "";
                for($x = 0; $x < $curSpaces; $x++) {
                    $recordBlankSpaces .= " ";
                }

                //calculate blank spaces for the record ttl so they lign up neatly
                $curSpaces = 10 - strlen($ttl) + 4;
                $recordTTLBlankSpaces = "";
                for($x = 0; $x < $curSpaces; $x++) {
                    $recordTTLBlankSpaces .= " ";
                }

                

                $out .= "$recName$blankSpaces $ttl$recordTTLBlankSpaces" . "IN      $recordType$recordBlankSpaces" . $entry["value"] . "\n";
            }
        }
        $out .= "\n\n";
    }

    if(strlen($out) < 3){
        return null;
    }else{
        return $out;
    }
}

function bind9_zonedb_generate_default($zone, $server){
    if(empty($zone)){
        header("HTTP/1.1 400 Bad request!");
        echo "<h1>DNS zone cannot be an empty string bind9_zonedb_generate()</h1>";
        exit(0);
        return;
    }
    $SOA = $zone;
    if(!preg_match("/\.{1}$/", $zone)){
        $SOA = "$SOA.";
    }
    if(!str_ends_with($server, ".")){
        $server .= ".";
    }
    return array(
        "DEFAULT_TTL" => 60,
        "SOA" => $SOA,
        "SOA_SERVER" => $server,
        "SERIAL" => 0,
        "REFRESH" => 3600,
        "RETRY" => 31536000,
        "EXPIRE" => 604800,
        "NEGATIVE_CACHE_TTL" => 300,
        "recordset" => array(),
    );
}